#!/usr/bin/env python3
"""Write a set's MODELDEF from its Model Card's own `model` / `skin` / `prop` lines.

    python _pending/tools/make_modeldef.py --card WMCARD.ww2 --out ww2/MODELDEF.txt --set RTCW

WHY THIS IS GENERATED AND NEVER WRITTEN BY HAND. A MODELDEF block and a card both name the mesh a
gun draws, and two statements of one fact drift. They did once: the WW2 cards moved onto `_wm`
meshes while the MODELDEF still named the originals, so sixteen models packed that nothing
addressed and nothing drew -- with no error anywhere, because a MODELDEF block naming a file that
exists is valid whether or not any card agrees.

WMPR is the reload system's one-pixel prop sprite: the frame WM_Prop's Spawn state actually
carries, and what every prop block in the base pack binds. A sprite name with no lump behind it is
a reference to nothing.
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def arg(name, default=None):
    if name in sys.argv:
        return sys.argv[sys.argv.index(name) + 1]
    return default


def main():
    card = arg("--card")
    out = arg("--out")
    setname = arg("--set", "")
    if not card or not out:
        sys.exit("usage: make_modeldef.py --card WMCARD.<set> --out <set>/MODELDEF.txt [--set NAME]")

    text = io.open(os.path.join(HERE, card), encoding="utf-8").read()

    rows = []
    for blk in re.split(r'\nweapon ', text)[1:]:
        gun = re.match(r'"(\w+)"', blk).group(1)
        prop = re.search(r'^\s*prop\s*=\s*"([^"]+)"', blk, re.M)
        model = re.search(r'^\s*model\s*=\s*"([^"]+)"\s+"([^"]+)"', blk, re.M)
        skin = re.search(r'^\s*skin\s*=\s*"([^"]+)"\s+"([^"]+)"', blk, re.M)
        if not (prop and model):
            print("  skip %s: no prop or no model line" % gun)
            continue
        if not skin:
            sys.exit("%s names a model but no skin -- refusing to write a block that draws untextured" % gun)
        if model.group(1) != skin.group(1):
            print("  note %s: model and skin sit in different folders (%s / %s)"
                  % (gun, model.group(1), skin.group(1)))
        # THE CARD'S OWN DRAW SCALE, default 1.0. It lives on the card because this file is
        # GENERATED from the card -- a scale stated anywhere else is silently reset to 1 on the
        # next regenerate, which is the exact drift this generator exists to prevent.
        # READ FROM A COMMENT, because the ENGINE'S card parser refuses an unknown key and
        # skips the whole weapon -- `modelscale` as a real key cost us a failed compile.
        # A comment is invisible to parser.zs and perfectly visible here, so the number
        # still lives on the card and still survives a regenerate.
        mscale = re.search(r'^\s*#\s*modelscale\s*=\s*([0-9.]+)', blk, re.M)
        rows.append((gun, prop.group(1), model.group(1), model.group(2), skin.group(2),
                     float(mscale.group(1)) if mscale else 1.0))

    if not rows:
        sys.exit("no cards with a prop and a model in %s" % card)

    label = (setname + " SET'S") if setname else "SET'S"
    o = []
    o.append("// ==========================================================================")
    o.append("// THE %s MODELS -- one block per gun, binding its mesh to the prop its card names." % label)
    o.append("//")
    o.append("// GENERATED by _pending/tools/make_modeldef.py from %s's OWN model and skin lines, so" % card)
    o.append("// the two cannot disagree about which file a gun draws. They did once: the card moved onto")
    o.append("// _wm meshes while this still named the originals, which packs models nothing addresses and")
    o.append("// draws nothing, with no error anywhere. DO NOT EDIT -- change the card and run it again.")
    o.append("//")
    o.append("// WMPR is the reload system's one-pixel prop sprite -- the frame WM_Prop's Spawn state")
    o.append("// carries, and what every prop block in the base pack binds. A name with no sprite lump")
    o.append("// behind it is a MODELDEF reference to nothing.")
    o.append("// ==========================================================================")
    o.append("")
    for gun, prop, path, mesh, skin, msc in rows:
        o.append("Model %s" % prop)
        o.append("{")
        o.append('\tPath "%s"' % path)
        o.append('\tModel 0 "%s"' % mesh)
        o.append('\tSkin 0 "%s"' % skin)
        o.append("\tScale %.3f %.3f %.3f" % (msc, msc, msc))
        o.append("\tOffset 0.0 0.0 0.0")
        o.append("\tAngleOffset 0.0")
        o.append("\tPitchOffset 0.0")
        o.append("\tRollOffset 0.0")
        o.append("\tNoInterpolation")
        o.append("\tFollowMainHand")
        o.append("\tFrameIndex WMPR A 0 0")
        o.append("}")
        o.append("")

    dest = os.path.join(HERE, out)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    io.open(dest, "w", encoding="utf-8", newline="\n").write("\n".join(o))
    print("make_modeldef: %d block(s) from %s -> %s" % (len(rows), card, out))


main()
