#!/usr/bin/env python3
"""SW_SaberLights.pk3 -- an OPTIONAL add-on for SW_VR_Xim / SW_VR_Wardusted: the lightsaber lights the room
from its BLADE, not from a point in front of you.

    python make_sw_saberlights.py [OUT_DIR]

The owner, 2026-09-29: "a tasteful directional dynamic light coming out of the hilt that fades at the top of
the blade ... optimize it so it pulses and flickers some".

A LINE OF LIGHT, IN STOCK QUESTZDOOM. There is no line light there, so the blade is a short chain of small,
attenuated point lights from the hilt to the tip, each dimmer and tighter than the last -- the light falls
away up the blade. Each pulses or flickers on its own interval (none share a period), so the blade breathes
instead of strobing. `sw_saberlights` 0/1/2: off / one light at mid-blade / the full chain of four.

ON THE BLADE, NOT AHEAD OF YOU. QuestZDoom gives scripts the controller: AttackPos, AttackAngle,
AttackPitch, AttackRoll. The chain runs from the hand along the blade's direction -- the aim, tipped by the
pose the HUD saber is drawn in for the frame on screen (the same pose table the model packs were built
from), so it follows the swing too.

SEPARATE, BECAUSE OF THOSE FIELDS: a QuestZDoom without them cannot compile this, and a pack that fails to
compile takes the game down with it. So the model packs keep their simple player glow (ZScript 3.2, runs
anywhere) and switch it off by themselves when this add-on's cvar exists.

PLAYSIM, SERVER CVAR: the light carriers are actors, so whether they exist is the server's call, the same on
every machine in a netgame.
"""
import io, math, os, sys, zipfile
from PIL import Image

OUT = sys.argv[1] if len(sys.argv) > 1 else "."

# (mod, weapon class, gate, colour, [(sprite, letter, yaw, up)]) -- the poses make_sw_vrplus.py drew
REST = (0.0, 50.0)
WD = [("SABR", f) + REST for f in "CDGHI"] + [
    ("SABA", f, y, u) for f, (y, u) in [("A", (-15, 60)), ("B", (-30, 70)), ("C", (-40, 75)), ("D", (-45, 75)),
                                        ("E", (-40, 65)), ("F", (0, 35)), ("G", (40, 10)), ("H", (55, -5)),
                                        ("I", (35, 20)), ("J", (10, 45)), ("K", (-10, 60)), ("L", (-20, 65)),
                                        ("M", (0, 30)), ("N", (40, 5))]]
XIM = [("SAWG", f, y, u) for f, (y, u) in [("A", REST), ("B", REST), ("C", (0, 8)), ("D", REST), ("E", (-20, 72)),
                                           ("F", (-5, 90)), ("G", (5, 80)), ("H", (10, 60)), ("I", (12, 28)),
                                           ("J", (8, 12)), ("K", REST)]]
MODS = [("R", "Lightsaber", False, (1.00, 0.16, 0.10), WD),      # Wardusted: red
        ("B", "Chainsaw",   True,  (0.32, 0.52, 1.00), XIM)]     # Xim: blue -- Doom's chainsaw, only in Xim

# THE CHAIN: where along the blade (0 hilt .. 1 tip), how big, how bright, and how it moves. Tasteful:
# small radii, attenuated, the tip a whisper. Four lights a saber at most -- Quest-friendly.
BLADE_LEN = 26.0            # map units: the HUD saber's ~75 cm blade, as the hand frame draws it
CHAIN = [  # (t, size, secondary, brightness, kind, interval)
    (0.10, 30, 36, 1.00, "pulselight",    0.53),
    (0.38, 28, 34, 0.85, "flickerlight2", 0.13),
    (0.66, 22, 27, 0.60, "pulselight",    0.37),
    (0.92, 13, 17, 0.38, "flickerlight2", 0.09),
]
MID = (0.50, 40, 48, 0.95, "pulselight", 0.45)          # the one light of "simple"


def png1():
    b = io.BytesIO(); Image.new("RGBA", (1, 1), (0, 0, 0, 0)).save(b, "PNG"); return b.getvalue()


def main():
    files = {}
    # ---- lights ---------------------------------------------------------------------------------------
    g = ["// GENERATED by make_sw_saberlights.py -- a line of light up the blade, fading to the tip.", ""]
    zs_classes = []
    for tag, *_ , rgb, _poses in [(m[0], m[1], m[2], m[3], m[4]) for m in MODS]:
        for n, (t, s1, s2, k, kind, iv) in enumerate(CHAIN + [MID]):
            name = "SWSL_%s%d" % (tag, n)
            col = tuple(c * k for c in rgb)
            g += ["%s %s" % (kind, name), "{", "\tcolor %.3f %.3f %.3f" % col, "\tsize %d" % s1,
                  "\tsecondarySize %d" % s2, "\tinterval %.2f" % iv, "\tattenuate 1", "}", ""]
            spr = "SL%s%d" % (tag, n)          # a sprite per light: SLR0..SLR4, SLB0..SLB4
            files["sprites/%sA0.png" % spr] = png1()
            g += ["object %s" % name, "{", "\tframe %sA { light %s }" % (spr, name), "}", ""]
            zs_classes.append((name, spr))
    files["GLDEFS"] = "\n".join(g).encode()

    # ---- zscript --------------------------------------------------------------------------------------
    z = ['version "4.0"', "",
         "// GENERATED by make_sw_saberlights.py. See its header.", ""]
    for name, spr in zs_classes:
        z += ["class %s : Actor" % name, "{", "\tDefault { +NOINTERACTION +NOGRAVITY +NOBLOCKMAP +DONTSPLASH +NOTONAUTOMAP }",
              "\tStates { Spawn: %s A -1; Stop; }" % spr, "}", ""]
    z += ["class SWSL_Handler : EventHandler", "{",
          "\tArray<Actor> lights;",
          "\tint ximKnown;", "",
          "\tprivate bool IsXim()", "\t{",
          "\t\tif (ximKnown == 0)", "\t\t{",
          '\t\t\tString s = StringTable.Localize("$GOTCHAINSAW");',
          "\t\t\ts = s.MakeLower();",
          '\t\t\tximKnown = (s.IndexOf("lightsaber") >= 0) ? 1 : 2;',
          "\t\t}", "\t\treturn ximKnown == 1;", "\t}", ""]
    # pose lookup per mod: returns yaw/up via a packed Vector2, and whether the frame shows a lit blade
    for tag, cls, gate, rgb, poses in MODS:
        z += ["\t// the pose the HUD saber is drawn in for this psprite frame (x yaw, y up); false: no blade",
              "\t// Returned as (yaw, up, 1), all 0 for no blade -- not through `out` parameters, which have faulted",
              "\t// in play on these engines.",
              "\tprivate Vector3 Pose%s(SpriteID spr, int frm)" % tag, "\t{"]
        for spr_name in sorted({p[0] for p in poses}):
            z += ['\t\tif (spr == Actor.GetSpriteIndex("%s"))' % spr_name, "\t\t{", "\t\t\tswitch (frm)", "\t\t\t{"]
            for s, f, y, u in poses:
                if s == spr_name:
                    z.append("\t\t\tcase %d: return (%.1f, %.1f, 1);" % (ord(f) - 65, y, u))
            z += ["\t\t\t}", "\t\t}"]
        z += ["\t\treturn (0, 0, 0);", "\t}", ""]
    z += ["\tprivate void Clear(int i)", "\t{", "\t\tif (lights.Size() < (i + 1) * 5) return;",
          "\t\tfor (int k = 0; k < 5; k++)", "\t\t{",
          "\t\t\tif (lights[i * 5 + k]) lights[i * 5 + k].Destroy();", "\t\t\tlights[i * 5 + k] = null;", "\t\t}", "\t}", "",
          "\toverride void WorldTick()", "\t{",
          '\t\tlet cv = CVar.FindCVar("sw_saberlights");',
          "\t\tint mode = cv ? cv.GetInt() : 2;",
          "\t\tif (lights.Size() < MAXPLAYERS * 5) lights.Resize(MAXPLAYERS * 5);",
          "\t\tstatic const double T[] = { %s };" % ", ".join("%.2f" % v for v in [c[0] for c in CHAIN] + [MID[0]]),
          "\t\tfor (int i = 0; i < MAXPLAYERS; i++)", "\t\t{",
          "\t\t\tif (!playeringame[i] || mode <= 0) { Clear(i); continue; }",
          "\t\t\tlet p = players[i];",
          "\t\t\tlet mo = p.mo;",
          "\t\t\tif (!mo || p.health <= 0 || !p.ReadyWeapon) { Clear(i); continue; }",
          "\t\t\tString tag = \"\";",
          "\t\t\tName wc = p.ReadyWeapon.GetClassName();",
          ]
    for tag, cls, gate, rgb, poses in MODS:
        cond = "wc == '%s'" % cls + (" && IsXim()" if gate else "")
        z.append('\t\t\tif (%s) tag = "%s";' % (cond, tag))
    z += ["\t\t\tif (tag == \"\") { Clear(i); continue; }",
          "\t\t\tlet psp = p.FindPSprite(PSP_WEAPON);",
          "\t\t\tVector3 pose = (0, 0, 0);",
          "\t\t\t// (pose read below)",
          "\t\t\tif (psp)", "\t\t\t{"]
    for tag, *_ in MODS:
        z.append('\t\t\t\tif (tag == "%s") pose = Pose%s(psp.Sprite, psp.Frame);' % (tag, tag))
    z += ["\t\t\t}",
          "\t\t\tif (pose.z == 0) { Clear(i); continue; }", "\t\t\tdouble yaw = pose.x, up = pose.y;",
          "",
          "\t\t\t// THE HAND'S AXES. AttackAngle is stored as (heading - 90) and AttackPitch negated -- the",
          "\t\t\t// engine's own convention; up is level up rolled about the aim by the wrist.",
          "\t\t\tdouble a = mo.AttackAngle + 90.0, pt = -mo.AttackPitch, r = mo.AttackRoll;",
          "\t\t\tVector3 f = (cos(pt) * cos(a), cos(pt) * sin(a), -sin(pt));",
          "\t\t\tVector3 flatRight = (sin(a), -cos(a), 0);",
          "\t\t\tVector3 levelUp = flatRight cross f;",
          "\t\t\tVector3 upv = levelUp * cos(r) - flatRight * sin(r);",
          "\t\t\tVector3 right = flatRight * cos(r) + levelUp * sin(r);",
          "\t\t\t// THE BLADE: the aim raised by `up`, swung by `yaw` (left positive) -- the pose's own order",
          "\t\t\tVector3 dir = f * (cos(up) * cos(yaw)) - right * (cos(up) * sin(yaw)) + upv * sin(up);",
          "\t\t\tVector3 hand = mo.AttackPos;",
          "\t\t\tif (hand == (0, 0, 0)) hand = mo.Vec3Offset(0, 0, p.viewheight * 0.8);   // no controller: flat",
          "",
          "\t\t\tint first = (mode >= 2) ? 0 : 4, last = (mode >= 2) ? 3 : 4;",
          "\t\t\tfor (int k = 0; k < 5; k++)", "\t\t\t{",
          "\t\t\t\tint s = i * 5 + k;",
          "\t\t\t\tif (k < first || k > last) { if (lights[s]) lights[s].Destroy(); lights[s] = null; continue; }",
          ]
    ts = [c[0] for c in CHAIN] + [MID[0]]
    z += [
          "\t\t\t\tVector3 at = hand + dir * (%.1f * T[k]);" % BLADE_LEN,
          '\t\t\t\tString cls = String.Format("SWSL_%s%d", tag, k);',
          "\t\t\t\tName want = cls;", "\t\t\t\tif (lights[s] && lights[s].GetClassName() != want) { lights[s].Destroy(); lights[s] = null; }",
          "\t\t\t\tif (!lights[s]) lights[s] = Actor.Spawn(cls, at);",
          "\t\t\t\telse lights[s].SetOrigin(at, true);",
          "\t\t\t}", "\t\t}", "\t}", "}", ""]
    files["zscript.txt"] = "\n".join(z).encode()
    files["CVARINFO"] = (b"// THE SABER'S BLADE LIGHT: 0 off, 1 one light at mid-blade, 2 a line of four fading to the tip.\n"
                         b"// A server setting -- the light carriers are actors, so every machine must agree.\n"
                         b"server int sw_saberlights = 2;\n")
    files["MENUDEF"] = b'''OptionValue "SWSL_Modes"
{
	0, "Off"
	1, "Simple (one light)"
	2, "Full (fades up the blade)"
}
OptionMenu "SWSL_Options"
{
	Title "LIGHTSABER LIGHT"
	StaticText "The blade lights the room, brightest at the hilt.", 1
	Option "Blade light", "sw_saberlights", "SWSL_Modes"
}
AddOptionMenu "OptionsMenu"
{
	Submenu "Lightsaber light", "SWSL_Options"
}
'''
    files["MAPINFO"] = b'GameInfo\n{\n\tAddEventHandlers = "SWSL_Handler"\n}\n'
    dest = os.path.join(OUT, "SW_SaberLights.pk3")
    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as zo:
        for k in sorted(files):
            zo.writestr(k, files[k])
    print(dest, len(files), "entries")


if __name__ == "__main__":
    main()
