#!/usr/bin/env python3
"""Write a set's CVARINFO -- the placement sliders, one set of ten per gun.

    python _pending/tools/make_cvarinfo.py --card WMCARD.bwolf --out bwolf/CVARINFO.txt --set BWolf

WHY THIS EXISTS. A gun draws where its PlacementCVars say it draws. Vanilla and Vanilla+ name a
set each -- wm_pumpm37, wm_chaingun -- and thirty-three of those thirty-three sets carry
`_yaw = -90.0`, because that is the turn from the mesh's own axes into the hand's.

THE BWOLF AND WW2 SETS SHIPPED WITH NO PLACEMENT CVARS AT ALL. make_modeldef never emitted a
PlacementCVars line and no add-on shipped a CVARINFO lump, so all thirty-five guns drew at their
raw mesh orientation. The owner found it wearing the headset -- "WHY ARE MY BWOLF GUNS FACING 90
TO THE RIGHT" -- and the answer was ninety degrees of missing default, in a file that did not
exist.

THE NUMBERS HERE ARE A STARTING POSE, NOT A MEASUREMENT. yaw -90 is the whole package's
convention and is certainly right; the offsets are the middle of what the owner tuned the base
pack's guns to (ofs_y 28.5, ofs_z 8.0) and are certainly approximate. They exist so a gun lands
in the hand facing forward and the sliders have somewhere to start, which is the difference
between a gun the owner can tune and a gun they cannot see.

CVARINFO ACCUMULATES ACROSS ARCHIVES, like SNDINFO and MODELDEF, so a set's lump sits beside the
base pack's rather than standing in for it. A name declared twice is the error to avoid, which is
why every stem here is prefixed by its set.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# The starting pose. See the header: the yaw is the package's convention, the offsets are the
# middle of the base pack's tuned values, and every one of them is a slider.
DEFAULTS = [("ofs_x", "0.0"), ("ofs_y", "28.5"), ("ofs_z", "8.0"),
            ("yaw", "-90.0"), ("pitch", "0.0"), ("roll", "0.0"),
            ("scale", "1.0"), ("scale_x", "1.0"), ("scale_y", "1.0"), ("scale_z", "1.0")]


def arg(name, default=None):
    return sys.argv[sys.argv.index(name) + 1] if name in sys.argv else default


def stem(prop):
    """WM_PropPumpM37 -> wm_pumpm37. Must agree with make_modeldef.stem or the name resolves to
    nothing and the gun is unplaced again, silently."""
    return prop.lower().replace("prop", "", 1).replace("__", "_").strip("_")


def main():
    card, out, setname = arg("--card"), arg("--out"), arg("--set", "")
    if not card or not out:
        sys.exit("usage: make_cvarinfo.py --card WMCARD.<set> --out <set>/CVARINFO.txt [--set NAME]")

    text = io.open(os.path.join(HERE, card), encoding="utf-8").read()
    props = []
    for blk in re.split(r'\nweapon ', text)[1:]:
        gun = re.match(r'"(\w+)"', blk).group(1)
        p = re.search(r'^\s*prop\s*=\s*"([^"]+)"', blk, re.M)
        if p:
            props.append((gun, p.group(1)))
    if not props:
        sys.exit("no props in %s" % card)

    seen = {}
    for gun, prop in props:
        s = stem(prop)
        if s in seen:
            sys.exit("%s and %s both reduce to the cvar stem `%s` -- two guns sharing one set of "
                     "sliders means tuning either moves both" % (seen[s], gun, s))
        seen[s] = gun

    label = (setname + " SET'S") if setname else "SET'S"
    o = ["// ==========================================================================",
         "// THE %s PLACEMENT SLIDERS -- ten per gun, the set its MODELDEF names." % label,
         "//",
         "// GENERATED by _pending/tools/make_cvarinfo.py from %s's prop names, so a gun's" % card,
         "// PlacementCVars line and its cvars cannot disagree. DO NOT EDIT -- a value tuned here is",
         "// overwritten on the next regenerate. TUNE IN THE HEADSET: these are user cvars and the",
         "// sliders write them to the ini, which is the copy that wins.",
         "//",
         "// yaw = -90 IS THE PACKAGE'S CONVENTION, not a guess -- all thirty-three tuned sets in the",
         "// base pack's CVARINFO carry it. The offsets are the middle of the base pack's own and are",
         "// a starting pose only.",
         "// ==========================================================================",
         ""]
    for gun, prop in props:
        s = stem(prop)
        o.append("// %s" % gun)
        for key, val in DEFAULTS:
            o.append("user float %s_%-7s = %s;" % (s, key, val))
        o.append("")

    dest = os.path.join(HERE, out)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    io.open(dest, "w", encoding="utf-8", newline="\n").write("\n".join(o))
    print("make_cvarinfo: %d gun(s) x %d cvars from %s -> %s"
          % (len(props), len(DEFAULTS), card, out))


main()
