#!/usr/bin/env python3
"""Write a set's MENUDEF -- one live placement page per gun, ten sliders each.

    python _pending/tools/make_menudef.py --card WMCARD.bwolf --out bwolf/MENUDEF.txt --set BWolf

WHY THIS EXISTS. Every add-on set now ships its own CVARINFO -- ten placement cvars per gun -- but
NO WAY TO REACH THEM. The owner found all 51 add-on guns seated wrong in the headset: "some are
rotated-like-a-cylinder 45, some are too high or low", and the answer to every one of those is a
slider that already exists behind no menu.

THEY MOVE LIVE, AND THAT IS THE WHOLE POINT. A menu FREEZES THE PLAYSIM, so a slider on a cvar that
only script reads moves nothing at all while you are looking at it -- which is the one moment it
exists for. The placement cvars are read by the RENDERER every frame, so dragging one moves the gun
in your hand with the menu still open. That distinction is what tools/menu_lint.py exists to
enforce (its E7), and a page is declared live to it by the `// LINT-LIVE:` line above it.

WHY A GENERATOR RATHER THAN A HAND-WRITTEN FILE. Ten sliders times 51 guns is 510 lines that must
each name a cvar that exists, spelled exactly as CVARINFO declares it. A typo produces a slider
that silently adjusts nothing -- which is the failure this package keeps finding in other shapes.
Both files come off the same card and the same stem() rule, so they cannot disagree.

THE ORDER OF THE SLIDERS IS THE ORDER YOU FIX THINGS IN. Position first, because a gun in the wrong
place is what you notice; then yaw, pitch and roll, because "rotated like a cylinder" is roll and it
should not be buried; then size. Reset buttons sit next to the group they reset rather than at the
bottom, so a bad drag costs one click.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def arg(name, default=None):
    return sys.argv[sys.argv.index(name) + 1] if name in sys.argv else default


def stem(prop):
    """Must agree with make_cvarinfo.stem and make_modeldef.stem, or every slider on the page
    names a cvar that does not exist and moves nothing."""
    return prop.lower().replace("prop", "", 1).replace("__", "_").strip("_")


def main():
    card, out, setname = arg("--card"), arg("--out"), arg("--set", "")
    if not card or not out:
        sys.exit("usage: make_menudef.py --card WMCARD.<set> --out <set>/MENUDEF.txt [--set NAME]")

    text = io.open(os.path.join(HERE, card), encoding="utf-8").read()
    guns = []
    for blk in re.split(r'\nweapon ', text)[1:]:
        g = re.match(r'"(\w+)"', blk).group(1)
        p = re.search(r'^\s*prop\s*=\s*"([^"]+)"', blk, re.M)
        if p:
            guns.append((g, stem(p.group(1))))
    if not guns:
        sys.exit("no props in %s" % card)

    label = setname or "SET"
    root = "WM_Place_%s" % (setname or "Set")
    o = ["// ==========================================================================",
         "// THE %s SET'S PLACEMENT PAGES -- where each gun sits in your hand." % label.upper(),
         "//",
         "// GENERATED by _pending/tools/make_menudef.py from %s, alongside that set's" % card,
         "// CVARINFO. Both come off the same card and the same stem rule, so a slider cannot name",
         "// a cvar that does not exist. DO NOT EDIT -- change the card and run it again.",
         "//",
         "// EVERY SLIDER HERE MOVES THE GUN WHILE THE MENU IS OPEN. These are renderer-read cvars;",
         "// a menu freezes the playsim, so a slider on a script-read cvar would move nothing at the",
         "// one moment it is wanted. That is what the LINT-LIVE lines declare and what menu_lint",
         "// checks.",
         "// ==========================================================================",
         "",
         "// LINT-LIVE: %s" % root,
         'OptionMenu "%s"' % root,
         "{",
         '\tTitle "%s -- WHERE EACH GUN SITS"' % label.upper(),
         '\tStaticText "Pick a gun, then drag. It moves in your hand as you drag it.", 1',
         '\tStaticText "Put the gun in your hand first -- you are adjusting what you can see.", "DarkGray"',
         '\tStaticText ""']
    for g, s in guns:
        o.append('\tSubmenu "%s", "%s_%s"' % (g, root, s))
    o += ["}", ""]

    # REACHABLE, OR IT MIGHT AS WELL NOT EXIST. An OptionMenu nothing links to cannot be opened.
    #
    # APPENDED TO THE ENGINE'S OWN OptionsMenu, NOT TO THE BASE PACK'S PAGE. An AddOptionMenu
    # naming a menu that does not exist STOPS THE ENGINE AT STARTUP, and a set must never be able
    # to do that to another package -- the base pack's own header says exactly this and it is the
    # reason it appends here too. OptionsMenu is the engine's and is always present.
    o += ['AddOptionMenu "OptionsMenu"',
          "{",
          '	Submenu "VR Weapons -- %s: where each gun sits", "%s"' % (label, root),
          "}", ""]

    for g, s in guns:
        page = "%s_%s" % (root, s)
        o += ["// LINT-LIVE: %s" % page,
              'OptionMenu "%s"' % page,
              "{",
              '\tTitle "%s"' % g.upper(),
              '\tStaticText "WHERE IT SITS ON YOUR CONTROLLER -- MOVES LIVE", "Gold"',
              '\tSlider "Left / right",   "%s_ofs_x", -100.0, 100.0, 0.25, 2' % s,
              '\tSlider "Forward / back", "%s_ofs_y", -100.0, 100.0, 0.25, 2' % s,
              '\tSlider "Down / up",      "%s_ofs_z", -100.0, 100.0, 0.25, 2' % s,
              '\tSafeCommand "Reset where it sits", "resetcvar %s_ofs_x; resetcvar %s_ofs_y; resetcvar %s_ofs_z"' % (s, s, s),
              '\tStaticText ""',
              '\tStaticText "HOW IT IS TURNED -- MOVES LIVE", "Gold"',
              '\tSlider "Yaw",   "%s_yaw",   -180, 180, 1, 0' % s,
              '\tSlider "Pitch", "%s_pitch", -180, 180, 1, 0' % s,
              '\tSlider "Roll",  "%s_roll",  -180, 180, 1, 0' % s,
              '\tStaticText "Roll is the one that fixes a gun rotated like a cylinder.", "DarkGray"',
              '\tSafeCommand "Reset how it is turned", "resetcvar %s_yaw; resetcvar %s_pitch; resetcvar %s_roll"' % (s, s, s),
              '\tStaticText ""',
              '\tStaticText "HOW BIG IT IS -- MOVES LIVE", "Gold"',
              '\tSlider "Size",         "%s_scale",   0.05, 4.0, 0.01, 2' % s,
              '\tSlider "Size along X", "%s_scale_x", 0.05, 3.0, 0.01, 2' % s,
              '\tSlider "Size along Y", "%s_scale_y", 0.05, 3.0, 0.01, 2' % s,
              '\tSlider "Size along Z", "%s_scale_z", 0.05, 3.0, 0.01, 2' % s,
              '\tStaticText "Above zero only -- the renderer ignores zero and below.", "DarkGray"',
              '\tSafeCommand "Reset its size", "resetcvar %s_scale; resetcvar %s_scale_x; resetcvar %s_scale_y; resetcvar %s_scale_z"' % (s, s, s, s),
              "}", ""]

    dest = os.path.join(HERE, out)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    io.open(dest, "w", encoding="utf-8", newline="\n").write("\n".join(o))
    print("make_menudef: %d gun page(s) + one index from %s -> %s" % (len(guns), card, out))


main()
