// ============================================================================================================
// THE BREACH SET (the owner, 2026-09-15: "go on the rest of the set. Get the Modern set finished").
// Generated by tools/gen_breach_set.py -- edit its table, not this file. Each gun: its shot from Breach's own zscript, its
// card in WMCARD.breach_set, its prop's MODELDEF block. Nothing 2D comes with them but Breach's icons; their muzzle flash,
// smoke and brass are RS_Ballistics', and every gun has its own (RS_Ballistics 0cc3ff5: glock17_sup, kimber1911, mk18,
// mk18_sup, hk416_sup, mcx_sup, g36c_sup, mp5, benelli_m4 -- one id across round, flash, ejecta and recoil).
// ============================================================================================================

// ============================================================================================================
// BREACH GLOCK (SUPPRESSED) -- MAIN HAND. glocks.zs:258: A_FireBullets(3, 3, 1, 20) aimed, ready again 6 tics later, semi-auto; one bullet on a fresh pull flies dead on (FirstShotsAccurate 1). Suppressed: ZBulletPuffSil and no alert.
// Its card is WMCARD.breach_set; its looks are RS_Ballistics' own 'glock17_sup' profiles -- round, flash, brass and recoil, one id (its suppressed look: a faint glow at the can, gas out of the port, a quiet room).
// ============================================================================================================
class WM_BreachGlockS : WM_Gun
{
	Default
	{
		WM_Gun.ShotSpread 3, 3;
		WM_Gun.ShotDamage 20, 60;
		WM_Gun.FireTics 6;
		WM_Gun.FirstShotsAccurate 1;
		WM_Gun.RoundProfile "glock17_sup";
		WM_Gun.FlashProfile "glock17_sup";
		WM_Gun.EjectaProfile "glock17_sup";
		WM_Gun.RecoilProfile "glock17_sup";
		Weapon.SelectionOrder 160;
		Weapon.SlotNumber 2;
		Inventory.PickupMessage "Glock (suppressed)";
		Tag "Glock (suppressed)";
		// Breach's own icon (graphics/GLOKB0.png): the weapon wheel shows AltHUDIcon first, then Icon.
		Inventory.Icon "GLOKB0";
		Inventory.AltHUDIcon "GLOKB0";
	}
}
class WM_PropBreachGlockS : WM_Prop {}

// ============================================================================================================
// BREACH KIMBER -- OFF HAND. kimber.zs:244: A_FireBullets(3, 3, 1, 34) aimed -- .45, 34 x 1d3 -- ready again 6 tics later, semi-auto; one bullet on a fresh pull flies dead on. OFF HAND, the Pistolet's seat.
// Its card is WMCARD.breach_set; its looks are RS_Ballistics' own 'kimber1911' profiles -- round, flash, brass and recoil, one id.
// ============================================================================================================
class WM_BreachKimber : WM_Gun
{
	Default
	{
		WM_Gun.ShotSpread 3, 3;
		WM_Gun.ShotDamage 34, 102;
		WM_Gun.FireTics 6;
		WM_Gun.FirstShotsAccurate 1;
		WM_Gun.RoundProfile "kimber1911";
		WM_Gun.FlashProfile "kimber1911";
		WM_Gun.EjectaProfile "kimber1911";
		WM_Gun.RecoilProfile "kimber1911";
		+WEAPON.OFFHANDWEAPON
		Weapon.SelectionOrder 9100;
		Weapon.SlotNumber 2;
		Inventory.PickupMessage "Kimber";
		Tag "Kimber";
		// Breach's own icon (graphics/KIMBER.png): the weapon wheel shows AltHUDIcon first, then Icon.
		Inventory.Icon "KIMBER";
		Inventory.AltHUDIcon "KIMBER";
	}
}
class WM_PropBreachKimber : WM_Prop {}

// ============================================================================================================
// BREACH MK18 -- MAIN HAND. mk18.zs:255: A_FireBullets(3.00, 3.00, -1, 30) aimed -- one bullet, always within that spread, 30 x 1d3 -- ready again 3 tics later (700 a minute). Breach toggles semi and full (rof_firemode); here the second button steps single, burst, full (AltMode selectfire).
// Its card is WMCARD.breach_set; its looks are RS_Ballistics' own 'mk18' profiles -- round, flash, brass and recoil, one id.
// ============================================================================================================
class WM_BreachMK18 : WM_Gun
{
	Default
	{
		WM_Gun.ShotSpread 3, 3;
		WM_Gun.ShotDamage 30, 90;
		WM_Gun.FireTics 3;
		WM_Gun.AltMode "selectfire";
		WM_Gun.AltBurst 3;
		WM_Gun.AltBurstTics 3;
		WM_Gun.RoundProfile "mk18";
		WM_Gun.FlashProfile "mk18";
		WM_Gun.EjectaProfile "mk18";
		WM_Gun.RecoilProfile "mk18";
		Weapon.SelectionOrder 900;
		Weapon.SlotNumber 4;
		Inventory.PickupMessage "MK18";
		Tag "MK18";
		// Breach's own icon (graphics/MKUSA0.png): the weapon wheel shows AltHUDIcon first, then Icon.
		Inventory.Icon "MKUSA0";
		Inventory.AltHUDIcon "MKUSA0";
	}
}
class WM_PropBreachMK18 : WM_Prop {}

// ============================================================================================================
// BREACH MK18 (SUPPRESSED) -- MAIN HAND. mk18s.zs:250: A_FireBullets(3.00, 3.00, -1, 30) aimed -- one bullet, always within that spread, 30 x 1d3 -- ready again 3 tics later (700 a minute). Breach toggles semi and full (rof_firemode); here the second button steps single, burst, full (AltMode selectfire).
// Its card is WMCARD.breach_set; its looks are RS_Ballistics' own 'mk18_sup' profiles -- round, flash, brass and recoil, one id (its suppressed look: a faint glow at the can, gas out of the port, a quiet room).
// ============================================================================================================
class WM_BreachMK18S : WM_Gun
{
	Default
	{
		WM_Gun.ShotSpread 3, 3;
		WM_Gun.ShotDamage 30, 90;
		WM_Gun.FireTics 3;
		WM_Gun.AltMode "selectfire";
		WM_Gun.AltBurst 3;
		WM_Gun.AltBurstTics 3;
		WM_Gun.RoundProfile "mk18_sup";
		WM_Gun.FlashProfile "mk18_sup";
		WM_Gun.EjectaProfile "mk18_sup";
		WM_Gun.RecoilProfile "mk18_sup";
		Weapon.SelectionOrder 910;
		Weapon.SlotNumber 4;
		Inventory.PickupMessage "MK18 (suppressed)";
		Tag "MK18 (suppressed)";
		// Breach's own icon (graphics/MK18A0.png): the weapon wheel shows AltHUDIcon first, then Icon.
		Inventory.Icon "MK18A0";
		Inventory.AltHUDIcon "MK18A0";
	}
}
class WM_PropBreachMK18S : WM_Prop {}

// ============================================================================================================
// BREACH HK416 (SUPPRESSED) -- MAIN HAND. hk416s.zs:247: A_FireBullets(1.75, 1.75, -1, 28) aimed -- one bullet, always within that spread, 28 x 1d3 -- ready again 3 tics later (700 a minute). Breach toggles semi and full (rof_firemode); here the second button steps single, burst, full (AltMode selectfire).
// Its card is WMCARD.breach_set; its looks are RS_Ballistics' own 'hk416_sup' profiles -- round, flash, brass and recoil, one id (its suppressed look: a faint glow at the can, gas out of the port, a quiet room).
// ============================================================================================================
class WM_BreachHK416S : WM_Gun
{
	Default
	{
		WM_Gun.ShotSpread 1.75, 1.75;
		WM_Gun.ShotDamage 28, 84;
		WM_Gun.FireTics 3;
		WM_Gun.AltMode "selectfire";
		WM_Gun.AltBurst 3;
		WM_Gun.AltBurstTics 3;
		WM_Gun.RoundProfile "hk416_sup";
		WM_Gun.FlashProfile "hk416_sup";
		WM_Gun.EjectaProfile "hk416_sup";
		WM_Gun.RecoilProfile "hk416_sup";
		Weapon.SelectionOrder 920;
		Weapon.SlotNumber 4;
		Inventory.PickupMessage "HK416 (suppressed)";
		Tag "HK416 (suppressed)";
		// Breach's own icon (graphics/HK416.png): the weapon wheel shows AltHUDIcon first, then Icon.
		Inventory.Icon "HK416";
		Inventory.AltHUDIcon "HK416";
	}
}
class WM_PropBreachHK416S : WM_Prop {}

// ============================================================================================================
// BREACH MCX (SUPPRESSED) -- MAIN HAND. mcx.zs:248: A_FireBullets(2.00, 2.00, -1, 28) aimed -- one bullet, always within that spread, 28 x 1d3 -- ready again 3 tics later (700 a minute). Breach toggles semi and full (rof_firemode); here the second button steps single, burst, full (AltMode selectfire).
// Its card is WMCARD.breach_set; its looks are RS_Ballistics' own 'mcx_sup' profiles -- round, flash, brass and recoil, one id (its suppressed look: a faint glow at the can, gas out of the port, a quiet room).
// ============================================================================================================
class WM_BreachMCX : WM_Gun
{
	Default
	{
		WM_Gun.ShotSpread 2, 2;
		WM_Gun.ShotDamage 28, 84;
		WM_Gun.FireTics 3;
		WM_Gun.AltMode "selectfire";
		WM_Gun.AltBurst 3;
		WM_Gun.AltBurstTics 3;
		WM_Gun.RoundProfile "mcx_sup";
		WM_Gun.FlashProfile "mcx_sup";
		WM_Gun.EjectaProfile "mcx_sup";
		WM_Gun.RecoilProfile "mcx_sup";
		Weapon.SelectionOrder 930;
		Weapon.SlotNumber 4;
		Inventory.PickupMessage "MCX (suppressed)";
		Tag "MCX (suppressed)";
		// Breach's own icon (graphics/MCX.png): the weapon wheel shows AltHUDIcon first, then Icon.
		Inventory.Icon "MCX";
		Inventory.AltHUDIcon "MCX";
	}
}
class WM_PropBreachMCX : WM_Prop {}

// ============================================================================================================
// BREACH G36C (SUPPRESSED) -- MAIN HAND. g36c.zs:247: A_FireBullets(2.00, 2.00, -1, 28) aimed -- one bullet, always within that spread, 28 x 1d3 -- ready again 3 tics later (700 a minute). Breach toggles semi and full (rof_firemode); here the second button steps single, burst, full (AltMode selectfire).
// Its card is WMCARD.breach_set; its looks are RS_Ballistics' own 'g36c_sup' profiles -- round, flash, brass and recoil, one id (its suppressed look: a faint glow at the can, gas out of the port, a quiet room).
// ============================================================================================================
class WM_BreachG36C : WM_Gun
{
	Default
	{
		WM_Gun.ShotSpread 2, 2;
		WM_Gun.ShotDamage 28, 84;
		WM_Gun.FireTics 3;
		WM_Gun.AltMode "selectfire";
		WM_Gun.AltBurst 3;
		WM_Gun.AltBurstTics 3;
		WM_Gun.RoundProfile "g36c_sup";
		WM_Gun.FlashProfile "g36c_sup";
		WM_Gun.EjectaProfile "g36c_sup";
		WM_Gun.RecoilProfile "g36c_sup";
		Weapon.SelectionOrder 940;
		Weapon.SlotNumber 4;
		Inventory.PickupMessage "G36C (suppressed)";
		Tag "G36C (suppressed)";
		// Breach's own icon (graphics/G36C.png): the weapon wheel shows AltHUDIcon first, then Icon.
		Inventory.Icon "G36C";
		Inventory.AltHUDIcon "G36C";
	}
}
class WM_PropBreachG36C : WM_Prop {}

// ============================================================================================================
// BREACH MP5 -- MAIN HAND. mp5.zs:329: A_FireBullets(0.8, 0.8, -1, 20) aimed, ready again 3 tics later; Breach has semi, 3-round burst and full -- the second button steps them here (AltMode selectfire, a burst of 3, 3 tics apart).
// Its card is WMCARD.breach_set; its looks are RS_Ballistics' own 'mp5' profiles -- round, flash, brass and recoil, one id.
// ============================================================================================================
class WM_BreachMP5 : WM_Gun
{
	Default
	{
		WM_Gun.ShotSpread 0.8, 0.8;
		WM_Gun.ShotDamage 20, 60;
		WM_Gun.FireTics 3;
		WM_Gun.AltMode "selectfire";
		WM_Gun.AltBurst 3;
		WM_Gun.AltBurstTics 3;
		WM_Gun.RoundProfile "mp5";
		WM_Gun.FlashProfile "mp5";
		WM_Gun.EjectaProfile "mp5";
		WM_Gun.RecoilProfile "mp5";
		Weapon.SelectionOrder 950;
		Weapon.SlotNumber 4;
		Inventory.PickupMessage "MP5";
		Tag "MP5";
		// Breach's own icon (graphics/MP5.png): the weapon wheel shows AltHUDIcon first, then Icon.
		Inventory.Icon "MP5";
		Inventory.AltHUDIcon "MP5";
	}
}
class WM_PropBreachMP5 : WM_Prop {}

// ============================================================================================================
// BREACH BENELLI M4 -- MAIN HAND. benelli.zs:212: A_FireBullets(4.5, 5, 30, 15) aimed -- thirty pellets, 15 x 1d3 each -- and 16 tics to the next; Breach's Benelli fires again while the trigger is held (FullAuto here). It is SEMI-AUTO: the bolt cycles itself on every shot (the cycle's auto = onshot).
// Its card is WMCARD.breach_set; its looks are RS_Ballistics' own 'benelli_m4' profiles -- round, flash, brass and recoil, one id.
// ============================================================================================================
class WM_BreachBenelli : WM_Gun
{
	Default
	{
		WM_Gun.ShotPellets 30;
		WM_Gun.ShotSpread 4.5, 5;
		WM_Gun.ShotDamage 15, 45;
		WM_Gun.FireTics 16;
		WM_Gun.FullAuto true;
		WM_Gun.RoundProfile "benelli_m4";
		WM_Gun.FlashProfile "benelli_m4";
		WM_Gun.EjectaProfile "benelli_m4";
		WM_Gun.RecoilProfile "benelli_m4";
		Weapon.AmmoType1 "Shell";
		Weapon.SelectionOrder 1300;
		Weapon.SlotNumber 3;
		Inventory.PickupMessage "Benelli M4";
		Tag "Benelli M4";
		// Breach's own icon (graphics/BENNA0.png): the weapon wheel shows AltHUDIcon first, then Icon.
		Inventory.Icon "BENNA0";
		Inventory.AltHUDIcon "BENNA0";
	}
}
class WM_PropBreachBenelli : WM_Prop {}
