// ============================================================================================================
// THE MODERN CLASS -- on the New Game menu whenever RS_Modern is loaded (its MAPINFO: AddPlayerClasses). Generated by
// tools/gen_breach_set.py.
//
// A WM_Player (RS_VR_Weapons' loadout.zs), so everything that attaches to that class attaches to this one -- the hands and
// body, the wrist HUD, the reload system, the ballistics, the grenade and ShieldSaw grants -- and every `is 'WM_Player'` holds.
// ITS OWN START: the whole BREACH set, the Glock raised in the main hand and the Kimber in the off hand, both fists, 200 Clip
// and 50 Shell. The engine starts a class's start items afresh at the first Player.StartItem it declares, so the Vanilla
// arsenal is not carried. SLOTS as Breach's (player.zs:42-51): 2 the pistols, 3 the Benelli, 4 the rifles and the MP5 -- each
// with the Vanilla guns a Doom pickup hands this class (weaponset.zs: WeaponSet 0) after them. StartGuns names the Glock and the
// Kimber, so with wm_start_arsenal off the fresh-start trim keeps them (WM_WeaponSet.ApplyStart).
// ============================================================================================================

class RSM_PlayerModern : WM_Player
{
	Default
	{
		WM_Player.WeaponSet 0;
		WM_Player.StartGuns "WM_BreachGlock", "WM_BreachKimber";
		Player.DisplayName "Modern";

		Player.StartItem "WM_BreachGlock";
		Player.StartItem "WM_BreachKimber";
		Player.StartItem "RS_WorldFist";
		Player.StartItem "RS_WorldFistOff";
		Player.StartItem "Clip", 200;
		Player.StartItem "Shell", 50;
		Player.StartItem "WM_BreachGlockS";
		Player.StartItem "WM_BreachMK18";
		Player.StartItem "WM_BreachMK18S";
		Player.StartItem "WM_BreachHK416S";
		Player.StartItem "WM_BreachMCX";
		Player.StartItem "WM_BreachG36C";
		Player.StartItem "WM_BreachMP5";
		Player.StartItem "WM_BreachBenelli";

		Player.WeaponSlot 2, "WM_BreachGlock", "WM_BreachGlockS", "WM_BreachKimber", "WM_M4A3", "WM_Pistolet";
		Player.WeaponSlot 3, "WM_BreachBenelli", "WM_PumpM37", "WM_PumpDoom", "WM_SSG", "WM_AssaultShotgun", "WM_BullpupPump";
		Player.WeaponSlot 4, "WM_BreachMK18", "WM_BreachMK18S", "WM_BreachHK416S", "WM_BreachMCX", "WM_BreachG36C", "WM_BreachMP5", "WM_Moonlight", "WM_Sunset", "WM_ColaRevolver";
	}
}
