// GENERATED by _pending/tools/gen_saber_blade.py. DO NOT EDIT -- change COLORS there.
//
// Every blade class, one per colour and hand. They differ only in name: the MODELDEF block
// with the same name is what gives each its colour.

class RS_SaberBlade_Blue : RS_SaberBladeProp {}
class RS_SaberBlade_Green : RS_SaberBladeProp {}
class RS_SaberBlade_Red : RS_SaberBladeProp {}
class RS_SaberBlade_Purple : RS_SaberBladeProp {}
class RS_SaberBlade_Yellow : RS_SaberBladeProp {}
class RS_SaberBlade_Orange : RS_SaberBladeProp {}
class RS_SaberBlade_Cyan : RS_SaberBladeProp {}
class RS_SaberBlade_White : RS_SaberBladeProp {}
class RS_SaberBladeOff_Blue : RS_SaberBladeProp {}
class RS_SaberBladeOff_Green : RS_SaberBladeProp {}
class RS_SaberBladeOff_Red : RS_SaberBladeProp {}
class RS_SaberBladeOff_Purple : RS_SaberBladeProp {}
class RS_SaberBladeOff_Yellow : RS_SaberBladeProp {}
class RS_SaberBladeOff_Orange : RS_SaberBladeProp {}
class RS_SaberBladeOff_Cyan : RS_SaberBladeProp {}
class RS_SaberBladeOff_White : RS_SaberBladeProp {}

// THE COLOUR LIST, IN rs_saber_color ORDER. Read by the handler to pick a class.
struct RS_SaberColors
{
	static String ClassFor(int idx, bool off)
	{
		static const String NAMES[] = { "Blue", "Green", "Red", "Purple", "Yellow", "Orange", "Cyan", "White" };
		idx = clamp(idx, 0, NAMES.Size() - 1);
		return String.Format("RS_SaberBlade%s_%s", off ? "Off" : "", NAMES[idx]);
	}

	// THE LIGHT'S COLOUR, per blade colour, so the walls glow what the blade is.
	static Color LightFor(int idx)
	{
		static const int R[] = { 110, 90, 255, 190, 255, 255, 80, 235 };
		static const int G[] = { 165, 255, 55, 90, 225, 140, 245, 240 };
		static const int B[] = { 255, 110, 45, 255, 80, 40, 255, 255 };
		idx = clamp(idx, 0, R.Size() - 1);
		return Color(R[idx], G[idx], B[idx]);
	}

	static int Count() { return 8; }
}
